name: Simple CI
on:
  push:
    branches: [ main, develop ]  # More triggers
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code          # Named steps
      uses: actions/checkout@v4
    - name: Set up Python          # Named steps
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies   # Named steps + error handling
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Run tests              # Conditional logic
      run: |
        if [ -d "tests" ]; then
          pytest tests/
        else
          echo "No tests folder found - skipping tests"
        fi
    - name: Test imports           # Extra validation
      run: |
        python -c "
        try:
            import src.main
            print('✅ Main module imports successfully')
        except Exception as e:
            print(f'❌ Import failed: {e}')
            exit(1)
        "